project:
  output-dir: _output
  render:
    - topics/**/*.md
    - answers/**/*.md

format:
  typst:
    papersize: a5
    margin:
      x: 1.4cm
      y: 1.4cm
    fontsize: 11pt
    include-in-header: templates/worksheet.typ
